#ifndef DEK_CAPABILITY_IDS_H
#define DEK_CAPABILITY_IDS_H

#define DEK_CAPABILITY_ID_UART_STREAM "uart.stream"
#define DEK_CAPABILITY_VERSION_UART_STREAM 1u

#define DEK_CAPABILITY_ID_GPIO_DIGITAL "gpio.digital"
#define DEK_CAPABILITY_VERSION_GPIO_DIGITAL 1u

#endif
